#pragma once

// Please don't change the content of this header, it is auto generated by CMAKE

#define PROJECT_SOURCE_DIR "C:/Users/wgumb/OneDrive/Documents/BCS 4th Year/2023 W1/CPSC 427/Project/code/"
